env: prod

user_home_path: "/home/{{ ansible_user }}"
venv_path: "{{ user_home_path }}/ansible_env"
venv_executable: "{{ venv_path }}/bin/python"


# db
main_db_user: "{{vault.postgres.master_username}}"
main_db_pass: "{{vault.postgres.master_password}}"
main_db_name: postgres
db_host: "{{vault.postgres.url}}"
