env: prod

user_home_path: "/home/{{ ansible_user }}"
venv_path: "{{ user_home_path }}/ansible_env"
venv_executable: "{{ venv_path }}/bin/python"


# db
main_db_user: "{{vault.postgres.master_username}}"
main_db_pass: "{{ lookup('amazon.aws.aws_secret', 'MAIN_DB_PASS', bypath=true).MAIN_DB_PASS }}"
main_db_name: postgres
db_host: "{{vault.postgres.url}}"

kafka_bootstrap_server_string: "{{ lookup('amazon.aws.aws_secret', 'KAFKA_BOOTSTRAP_STRING', bypath=true).KAFKA_BOOTSTRAP_STRING }}"

# kafka
kafka_topic: video-transcode-status

## this to be added dynamically from CI
publisher_docker_image_url: ""
transcoder_docker_image_url: ""
