env: prod

user_home_path: "/home/{{ ansible_user }}"
venv_path: "{{ user_home_path }}/ansible_env"
venv_executable: "{{ venv_path }}/bin/python"


# db
main_db_user: "{{vault.postgres.master_username}}"
main_db_pass: "{{ lookup('amazon.aws.aws_secret', 'MAIN_DB_PASS', bypath=true).MAIN_DB_PASS }}"
main_db_name: postgres
db_host: "{{vault.postgres.url}}"

kafka_bootstrap_server_string: "{{ lookup('amazon.aws.aws_secret', 'KAFKA_BOOTSTRAP_STRING', bypath=true).KAFKA_BOOTSTRAP_STRING }}"

# kafka
kafka_topic: video-transcode-status

## this to be added dynamically from CI
publisher_docker_image_url: "023231733398.dkr.ecr.eu-north-1.amazonaws.com/my-transcoding-example_uploader:45fc47757736b8ed7d3cc056d0956b95e5718de0"
transcoder_docker_image_url: "023231733398.dkr.ecr.eu-north-1.amazonaws.com/my-transcoding-example_transcoder:d13aaaf573d599dbaced6ade2557fe12da78cafc"
