# postgresql
main_db_user: "{{vault.postgres.master_username}}"
main_db_pass: "{{vault.postgres.master_password}}"
main_db_name: postgres
db_host: "{{vault.postgres.url}}"

postgresql_databases:
  - name: main_db
    state: present

  - name: transcode_db
    state: present

postgresql_users:
  - name: main_user
    password: "{{vault.postgres.users.publisher.password}}"

  - name: transcode_user
    password: "{{vault.postgres.users.transcoder.password}}"

postgresql_privs:
  - user: main_user
    main_db: main_db
    objs: ALL_IN_SCHEMA

  - user: transcode_user
    main_db: transcode_db
    objs: ALL_IN_SCHEMA
