
# postgresql
postgresql_databases:
  - name: main_db
    login_host: "{{vault.postgres.url}}"
    login_password: "{{vault.postgres.master_password}}"
    login_user: "{{vault.postgres.master_username}}"
    state: present

  - name: transcode_db
    login_host: "{{vault.postgres.url}}"
    login_password: "{{vault.postgres.master_password}}"
    login_user: "{{vault.postgres.master_username}}"
    state: present


postgresql_users:
  - name: main_user
    main_db: "{{ postgresql.main_db_name }}"
    password: "{{vault.postgres.users.publisher.password}}"
    login_host: "{{vault.postgres.url}}"
    login_password: "{{vault.postgres.master_password}}"
    login_user: "{{vault.postgres.master_username}}"

  - name: transcode_user
    main_db: "{{ postgresql.main_db_name }}"
    password: "{{vault.postgres.users.transcoder.password}}"
    login_host: "{{vault.postgres.url}}"
    login_password: "{{vault.postgres.master_password}}"
    login_user: "{{vault.postgres.master_username}}"

postgresql_privs:
  - user: main_user
    main_db: main_db
    objs: ALL_IN_SCHEMA
    login_host: "{{vault.postgres.url}}"
    login_password: "{{vault.postgres.master_password}}"
    login_user: "{{vault.postgres.master_username}}"

  - user: transcode_user
    main_db: transcode_db
    objs: ALL_IN_SCHEMA
    login_host: "{{vault.postgres.url}}"
    login_password: "{{vault.postgres.master_password}}"
    login_user: "{{vault.postgres.master_username}}"

