---

- name: all
  hosts: all
  vars_files:
    - environments/tf_ansible_vars_file.yml
  roles:
    - role: python
      tags: [ 'python' ]

    - role: postgresql
      tags: [ 'postgresql' ]

    - role: kafka
      tags: [ 'kafka', 'never' ]

    - role: publisher
      tags: [ 'never', 'publisher' ]

    - role: transcoder
      tags: [ 'never', 'transcoder' ]
