
name: deploy
run-name: provision the infrastructure
on:
  push:
    branches:
      - main
env:
  REGION: us-east-1

jobs:

  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Getting the artifact
        uses: ./.github/tf_artifact

      - name: Run Playbook
        uses: ./github/playbook
        with:
          role-to-assume: ${{ secrets.ROLEARN }}
          aws-region: ${{ env.REGION }}