name: triggered
run-name: triggered from another workflow
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'String specifying the ansible tags to run seperated by comma'
        required: true
      publisher_image:
        description: 'The image if set is required if the tags is publisher'

env:
  REGION: us-east-1

jobs:
  run-playbook:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: debug the input passed to the workflow from api
        run: |
          echo "${{ inputs.tags }}"

      - name: Getting the artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          repo: "go-transcoder/IaC"
          workflow: deploy.yml
          workflow_search: false
          workflow_conclusion: success
          branch: main
          name: tf_ansible_vars_file
          if_no_artifact_found: fail
          allow_forks: false
          path: ./provisioning/environments

      # debugging the tf_ansible_vars_file
      - run: |
          ls ./provisioning/environments/
          cat ./provisioning/environments/tf_ansible_vars_file.yml

      # login to aws to get secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: ${{ secrets.ROLEARN }}
          aws-region: ${{ env.REGION }}

      # Get the private key from secret manager
      - name: Step name
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            SSH_PRIVATE_KEY, PIVOT_KEY
            VAULT_PASS

      # Setting up python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: './requirements.txt'

      - name: "installing necessary packages"
        run: |
          pip install -r ./requirements.txt

      - name: Adding the ssh-key
        env:
          SSH_DEPLOY_KEY: ${{env.SSH_PRIVATE_KEY}}
        run: |
          touch .ansible_key
          echo "$SSH_DEPLOY_KEY" > .ansible_key
          chmod 600 .ansible_key

      - name: create the .vault_pass file
        env:
          VAULT_PASS: ${{env.VAULT_PASS}}
        run: |
          touch .vault_pass
          echo "$VAULT_PASS" > .vault_pass

      - name: Run the playbook
        env:
          PLAYBOOK_TAGS: ${{inputs.tags}}
          PUBLISHER_IMAGE: ${{inputs.publisher_image}}
        run: |
          ansible-playbook --vault-password-file .vault_pass --key-file .ansible_key -i provisioning/environments/prod/ provisioning/playbook.yml -t $PLAYBOOK_TAGS --extra-vars "publisher_docker_image_url=$PUBLISHER_IMAGE"
