name: triggered
run-name: triggered from another workflow
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'String specifying the ansible tags to run seperated by comma'
        required: true

jobs:
  run-playbook:
    runs-on: ubuntu-latest
    steps:
      - name: debug the input passed to the workflow from api
        run: |
          echo "${{ inputs.tags }}"

      - name: Getting the artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          repo: "go-transcoder/IaC"
          workflow: deploy.yml
          workflow_search: false
          workflow_conclusion: success
          branch: main
          name: tf_ansible_vars_file
          if_no_artifact_found: fail
          allow_forks: false
          path: ./provisioning/environments/tf_generated_vars.yml

      # here deploy
      # install the community.aws collection ansible-galaxy collection install community.aws