name: triggered
run-name: triggered from another workflow
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'String specifying the ansible tags to run seperated by comma'
        required: true
      extra-vars:
        description: 'Sometimes we might pass additional vars to be passed to the playbook'

env:
  REGION: us-east-1

jobs:
  run-playbook:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: debug the input passed to the workflow from api
        run: |
          echo "${{ inputs.tags }}"

      - name: Getting the artifact
        uses: ./.github/tf_artifact

      - name: Run Playbook
        uses: ./.github/playbook
        with:
          role-to-assume: ${{ secrets.ROLEARN }}
          aws-region: ${{ env.REGION }}
          playbook-tags: ${{ inputs.tags }}
          extra-vars: ${{ inputs.extra-vars }}
