---

- name: Set task_definition variable
  set_fact:
    td: "{{ publisher_service.task_definition }}"

# create the task definition
- name: Create the task definition
  community.aws.ecs_taskdefinition:
    state: "present"
    family: "{{ td.family }}"
    launch_type: "{{ td.launch_type }}"
    network_mode: "awsvpc"
    execution_role_arn: "{{ td.execution_role_arn }}"
    task_role_arn: "{{ td.task_role_arn }}"
    cpu: "{{ td.cpu }}"
    memory: "{{ td.memory }}"
    containers: "{{ td.containers }}"
    region: "{{ aws_region }}"
  register: task_output

- name: Print details Task name and revision
  debug:
    msg: "{{  task_output.taskdefinition[\"family\"]   }}:{{ task_output.taskdefinition[\"revision\"] }}"

# Create the service and assign the task definition to it
- name: Create the ecs service
  community.aws.ecs_service:
    state: present
    name: publisher-service
    cluster: "{{ publisher_service.cluster }}"
    launch_type: "{{ td.launch_type }}"
    task_definition: "{{  task_output.taskdefinition[\"family\"]   }}:{{ task_output.taskdefinition[\"revision\"] }}"
    desired_count: 1
    deployment_configuration: "{{ publisher_service.deployment_configuration }}"
    network_configuration: "{{ publisher_service.network_configuration }}"
    load_balancers: "{{ publisher_service.load_balancers }}"
    region: "{{ aws_region }}"
  register: service_output

